apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-dashboard-app-deployment
  labels:
    app: ai-dashboard-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-dashboard-app
  template:
    metadata:
      labels:
        app: ai-dashboard-app
    spec:
      containers:
      - name: ai-dashboard-app
        image: gcr.io/b-508911/ai-dashboard-app:latest
        ports:
        - containerPort: 8050
        resources:
          requests:
            cpu: 1000m
            memory: 6Gi
          limits:
            cpu: 1500m
            memory: 7.5Gi
        volumeMounts:
        - mountPath: /data
          name: app-storage
      volumes:
      - name: app-storage
        persistentVolumeClaim:
          claimName: app-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: pd-ssd