apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-dashboard-app-deployment
  labels:
    app: ai-dashboard-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-dashboard-app
  template:
    metadata:
      labels:
        app: ai-dashboard-app
    spec:
      securityContext:
        fsGroup: 2000
      containers:
      - name: ai-dashboard-app
        image: gcr.io/b-508911/ai-dashboard-app:latest
        ports:
        - containerPort: 8050
          name: http
        resources:
          requests:
            memory: "6Gi"
            cpu: "1000m"
          limits:
            memory: "10Gi"
            cpu: "2000m"
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 180
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 180
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        env:
        - name: PYTHONUNBUFFERED
          value: "1"